### ISSUE TITLE
Rules don't get updated when changing instance ownership

### ISSUE THREAD

**Issue by Teutone** [joyent/sdc-fwapi#3]
When changing ownership of an instance via adminui, firewall rules don't get updated / deleted. 
To reproduce:
- Create two accounts
- create inst in account 01
- transfer ownership of that inst to account 02
- `triton profile set account 01`
- `triton fwrule ls`

still shows old rules.

This is on HN PI `20190314T022529Z`
and `fwapi release-20190718-20190718T071429Z-gd63ff35`

**Comment by melloc** [comment]
Rules are considered account-level, and not part of an instance. Since a single rule can apply to many VMs by using tags, the `ALL VMS` keywords, or through combining multiple `vm` keywords, it's not safe to change the ownership of all rules that apply to an instance, since it may change behaviour for others VMs on both the source and destination accounts.

If you change the owner of an instance, you'll need to decide what rules you want to copy, and how they apply to the new account.

**Comment by Teutone** [comment]
Thank you for clarifying 👍
